import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from './models/Product.js';

dotenv.config();

await mongoose.connect(process.env.MONGODB_URI);

const products = [
  {
    id: 1,
    name: "Purple OUD",
    description: "A deep, luxurious oud blended with warm amber and exotic spices.",
    category: "Perfume",
    inspiredBy: "Purple Oud (Dior)",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Day/Night",
    family: "Amber Woody",
    accords: ["Woody", "Spicy", "Citrus", "Oud"],
    top: "Mandarin Orange",
    mid: "Pink Pepper, Saffron",
    base: "Oud (Agarwood)",
    price: 99,
    image: "purple_oud.jpg",
    images: ["purple_oud.jpg", "purple_oud1.jpg", "purple_oud2.jpg"]
  },

  {
    id: 2,
    name: "Pulse Royale",
    description: "Fresh aromatic notes with a smooth woody and masculine finish.",
    category: "Perfume",
    inspiredBy: "CR-7",
    gender: "Unisex",
    season: "All Season",
    time: "Day",
    family: "Aromatic Fougère",
    accords: ["Aromatic", "Woody", "Powdery", "Warm Spicy"],
    top: "Lavender, Cardamom, Artemisia, Bergamot",
    mid: "Tobacco, Cinnamon, Cedar, Iris",
    base: "Vanilla, Musk, Sandalwood, Amber",
    price: 99,
    image: "pulse_royale.jpg",
    images: ["pulse_royale.jpg", "pulse_royale1.jpg", "pulse_royale2.jpg"]
  },

  {
    id: 3,
    name: "Aqua Wave",
    description: "A fresh aquatic fragrance with citrus and marine notes. Clean, crisp and refreshing.",
    category: "Perfume",
    inspiredBy: "Acqua Di Gio",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day/Night",
    family: "Aromatic Aquatic",
    accords: ["Citrus", "Aromatic", "Marine", "Fresh Spicy"],
    top: "Lime, Lemon, Bergamot, Jasmine, Orange, Mandarin",
    mid: "Sea Notes, Jasmine, Calone, Peach, Freesia",
    base: "White Musk, Cedar, Oakmoss, Patchouli, Amber",
    price: 99,
    image: "aqua_wave.jpg",
    images: ["aqua_wave.jpg", "aqua_wave1.jpg", "aqua_wave2.jpg"]
  },

  {
    id: 4,
    name: "Eternal Elixir",
    description: "An intense spicy aromatic scent with powerful depth. Perfect for bold evenings.",
    category: "Perfume",
    inspiredBy: "Dior Sauvage Elixir",
    gender: "Male",
    season: "All Season",
    time: "Night",
    family: "Aromatic Spicy",
    accords: ["Warm Spicy", "Fresh Spicy", "Woody", "Aromatic"],
    top: "Nutmeg, Cinnamon, Cardamom, Grapefruit",
    mid: "Lavender",
    base: "Licorice, Sandalwood, Amber, Patchouli, Vetiver",
    price: 99,
    image: "eternal_elixir.jpg",
    images: ["eternal_elixir.jpg", "eternal_elixir1.jpg", "eternal_elixir2.jpg"]
  },

  {
    id: 5,
    name: "Golden Blush",
    description: "Soft florals with creamy vanilla and almond sweetness. Elegant and feminine.",
    category: "Perfume",
    inspiredBy: "Good Girl Blush",
    gender: "Female",
    season: "All Season",
    time: "Day",
    family: "Chypre Floral",
    accords: ["Floral", "Vanilla", "Citrus", "Powdery", "Almond"],
    top: "Bergamot, Bitter Almond",
    mid: "Peony, Ylang-Ylang",
    base: "Vanilla, Coumarin (Tonka)",
    price: 99,
    image: "golden_blush.jpg",
    images: ["golden_blush.jpg", "golden_blush1.jpg", "golden_blush2.jpg"]
  },

  {
    id: 6,
    name: "Intense Suede",
    description: "Warm spicy sweetness with smooth suede and vanilla. Sensual and addictive.",
    category: "Perfume",
    inspiredBy: "Stronger With You Intensely",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Fougère",
    accords: ["Warm Spicy", "Amber", "Vanilla", "Sweet"],
    top: "Pink Pepper, Juniper, Violet",
    mid: "Toffee, Cinnamon, Lavender, Sage",
    base: "Vanilla, Tonka Bean, Amber, Suede",
    price: 99,
    image: "intense_suede.jpg",
    images: ["intense_suede.jpg", "intense_suede1.jpg", "intense_suede2.jpg"]
  },

  {
    id: 7,
    name: "Cool Essence",
    description: "Crisp green freshness with citrus and woods. Sporty, clean and refreshing.",
    category: "Perfume",
    inspiredBy: "Polo Sport",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Green",
    accords: ["Aromatic", "Fresh Spicy", "Green", "Citrus"],
    top: "Mint, Aldehydes, Lavender, Bergamot, Mandarin, Lemon",
    mid: "Seagrass, Ginger, Jasmine, Geranium, Rosewood",
    base: "Musk, Sandalwood, Cedar, Guaiac Wood, Amber",
    price: 99,
    image: "cool_essence.jpg",
    images: ["cool_essence.jpg", "cool_essence1.jpg", "cool_essence2.jpg"]
  },

  {
    id: 8,
    name: "Divine Essence",
    description: "A luxurious vanilla-forward fragrance with aromatic warmth. Comforting yet powerful.",
    category: "Perfume",
    inspiredBy: "Burberry Goddess",
    gender: "Female",
    season: "All Season",
    time: "Day/Night",
    family: "Aromatic Gourmand",
    accords: ["Vanilla", "Aromatic", "Sweet", "Lavender"],
    top: "Vanilla Infusion, Lavender, Cacao, Ginger",
    mid: "Vanilla Caviar",
    base: "Vanilla Absolute",
    price: 99,
    image: "divine_essence.jpg",
    images: ["divine_essence.jpg", "divine_essence1.jpg", "divine_essence2.jpg"]
  },

  {
    id: 9,
    name: "Vanilla Blossom",
    description: "Sweet vanilla blended with florals and amber. Cozy, warm and irresistible.",
    category: "Perfume",
    inspiredBy: "Kayali Vanilla 28",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Vanilla",
    accords: ["Vanilla", "Sweet", "Amber", "Powdery", "Floral"],
    top: "Vanilla Orchid, Jasmine",
    mid: "Brown Sugar, Tonka Bean",
    base: "Amber, Amberwood, Musk, Patchouli",
    price: 99,
    image: "vanilla_blossom.jpg",
    images: ["vanilla_blossom.jpg", "vanilla_blossom1.jpg", "vanilla_blossom2.jpg"]
  },

  {
    id: 10,
    name: "Eternal Sauvage",
    description: "Fresh spicy citrus with aromatic woods. Powerful, masculine and long-lasting.",
    category: "Perfume",
    inspiredBy: "Dior Sauvage (EDT)",
    gender: "Male",
    season: "All Season",
    time: "Day/Night",
    family: "Aromatic Fougère",
    accords: ["Fresh Spicy", "Amber", "Citrus", "Aromatic"],
    top: "Calabrian Bergamot, Pepper",
    mid: "Sichuan Pepper, Lavender, Pink Pepper, Vetiver, Patchouli",
    base: "Ambroxan, Cedar, Labdanum",
    price: 99,
    image: "eternal_sauvage.jpg",
    images: ["eternal_sauvage.jpg", "eternal_sauvage1.jpg", "eternal_sauvage2.jpg"]
  },

  {
    id: 11,
    name: "Invictus",
    description: "Fresh aquatic scent with salty marine notes. Energetic, youthful and bold.",
    category: "Perfume",
    inspiredBy: "Invictus Aqua",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Woody Aquatic",
    accords: ["Citrus", "Marine", "Aquatic", "Salty"],
    top: "Yuzu, Grapefruit, Pink Pepper",
    mid: "Sea Water, Violet Leaf",
    base: "Ambergris, Amberwood, Guaiac Wood",
    price: 99,
    image: "invictus.jpg",
    images: ["invictus.jpg", "invictus1.jpg", "invictus2.jpg"]
  },

  {
    id: 12,
    name: "Bleu Voyage",
    description: "Citrus freshness balanced with woody incense notes. Sophisticated and timeless.",
    category: "Perfume",
    inspiredBy: "Bleu de Chanel",
    gender: "Male",
    season: "All Season",
    time: "Day/Night",
    family: "Woody Aromatic",
    accords: ["Citrus", "Woody", "Warm Spicy", "Aromatic"],
    top: "Grapefruit, Lemon, Mint, Pink Pepper",
    mid: "Ginger, Nutmeg, Jasmine, Iso E Super",
    base: "Incense, Vetiver, Cedar, Sandalwood, Patchouli",
    price: 99,
    image: "bleu_voyage.jpg",
    images: ["bleu_voyage.jpg", "bleu_voyage1.jpg", "bleu_voyage2.jpg"]
  },

  {
    id: 13,
    name: "Aventus",
    description: "Iconic fruity-smoky fragrance with woods and musk. Confident and commanding.",
    category: "Perfume",
    inspiredBy: "Creed Aventus",
    gender: "Male",
    season: "All Season",
    time: "Day/Night",
    family: "Chypre Fruity",
    accords: ["Fruity", "Sweet", "Leather", "Woody", "Smoky"],
    top: "Pineapple, Bergamot, Black Currant, Apple",
    mid: "Birch, Patchouli, Moroccan Jasmine, Rose",
    base: "Musk, Oakmoss, Ambergris, Vanilla",
    price: 99,
    image: "aventus.jpg",
    images: ["aventus.jpg", "aventus1.jpg", "aventus2.jpg"]
  },

  {
    id: 14,
    name: "Golden Flora",
    description: "Bright floral bouquet with fruity sweetness. Soft, joyful and elegant.",
    category: "Perfume",
    inspiredBy: "Gucci Flora Gorgeous Gardenia",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["White Floral", "Sweet", "Fruity", "Floral"],
    top: "Pear Blossom, Red Berries, Italian Mandarin",
    mid: "Gardenia, Jasmine, Frangipani",
    base: "Brown Sugar, Patchouli",
    price: 99,
    image: "golden_flora.jpg",
    images: ["golden_flora.jpg", "golden_flora1.jpg", "golden_flora2.jpg"]
  },

  {
    id: 15,
    name: "Fresh Impact",
    description: "Sparkling citrus with aromatic spice and woods. Clean, uplifting and modern.",
    category: "Perfume",
    inspiredBy: "Louis Vuitton Imagination",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Citrus Aromatic",
    accords: ["Citrus", "Aromatic", "Fresh Spicy", "Woody"],
    top: "Citron, Calabrian Bergamot, Sicilian Orange",
    mid: "Tunisian Neroli, Nigerian Ginger, Ceylon Cinnamon",
    base: "Chinese Black Tea, Ambroxan, Guaiac Wood, Olibanum",
    price: 99,
    image: "fresh_impact.jpg",
    images: ["fresh_impact.jpg", "fresh_impact1.jpg", "fresh_impact2.jpg"]
  },

  {
    id: 160,
    name: "Signature Discovery Set",
    description: "A curated set of bestsellers. Perfect for gifting or first-time discovery.",
    category: "Combo",
    inspiredBy: "Best Sellers Collection",
    gender: "Unisex",
    season: "All Season",
    time: "Day/Night",
    family: "Variety Pack",
    accords: ["Variety", "Gift", "Sample"],
    top: "Contains 4 x 8ml testers",
    mid: "Aventus, Purple OUD, Golden Blush, Eternal Elixir",
    base: "Perfect for gifting or travel",
    price: 999,
    image: "discovery_set.jpg",
    images: ["discovery_set.jpg", "discovery_set1.jpg", "discovery_set2.jpg"]
  },

  {
    id: 170,
    name: "His & Hers Gift Box",
    description: "A romantic fragrance duo crafted for couples. Luxury gifting made simple.",
    category: "Combo",
    inspiredBy: "Couple's Collection",
    gender: "Unisex",
    season: "All Season",
    time: "Night",
    family: "Gift Set",
    accords: ["Romantic", "Gift", "Luxury"],
    top: "1 x 50ml Eternal Elixir (Him)",
    mid: "1 x 50ml Golden Blush (Her)",
    base: "Premium Magnetic Gift Box Included",
    price: 999,
    image: "his_hers_gift.jpg",
    images: ["his_hers_gift.jpg", "his_hers_gift1.jpg", "his_hers_gift2.jpg"]
  },

  {
    id: 180,
    name: "Royal Oud Trilogy",
    description: "An intense oud collection for true connoisseurs. Rich, bold and exclusive.",
    category: "Combo",
    inspiredBy: "Oud Collection",
    gender: "Unisex",
    season: "Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Oud", "Intense", "Luxury"],
    top: "3 x 30ml Intense Oud Fragrances",
    mid: "Purple OUD, Imperial Oud, Saffron Gold",
    base: "Velvet Lined Box",
    price: 999,
    image: "royal_oud_trilogy.jpg",
    images: ["royal_oud_trilogy.jpg", "royal_oud_trilogy1.jpg", "royal_oud_trilogy2.jpg"]
  },
  {
    id: 15,
    name: "Chocolate Musk",
    image: "sweet chocolate gourmond.png",
    images: ["sweet chocolate gourmond.png", "chocolatem1.jpg", "chocolatem2.jpg", "info.jpga"],
    description: "A rich gourmand attar blending creamy chocolate with soft musk and powdery warmth, creating a comforting and addictive aroma.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Gourmand",
    accords: ["Gourmand", "Musky", "Powdery"],
    top: "Milk Chocolate, Cinnamon, Vanilla",
    mid: "Spicy Notes, Rose",
    base: "White Musk, Sandalwood, Myrrh, Amber",
    price: 49
  },
  // {
  //   id: 16,
  //   name: "Iceberg",
  //   image: "iceberg.jpg",
  //   images: ["iceberg.jpg", "iceberg1.jpg", "iceberg2.jpg", "info.jpg"],
  //   description: "A crisp and refreshing citrus fragrance with green freshness and subtle florals, delivering a clean and classic masculine profile.",
  //   category: "Perfume",
  //   inspiredBy: "",
  //   gender: "Male",
  //   season: "Spring-Summer",
  //   time: "Day",
  //   family: "Fresh Citrus",
  //   accords: ["Citrus", "Fresh", "Floral"],
  //   top: "Galbanum, Bergamot, Basil, Orange Blossom, Lemon, Peach",
  //   mid: "Lily, Lily-of-the-Valley, Jasmine, Orris Root, Rose, Ylang-Ylang",
  //   base: "Oakmoss, Cedar, Vetiver, Sandalwood, Musk, Amber",
  //   price: 69
  // },
  {
    id: 17,
    name: "Iceberg",
    image: "Fresh_auqatic.png",
    images: ["Fresh_auqatic.png", "iceberga1.jpg", "iceberga2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a fresh citrus floral fragrance, offering enhanced longevity and smooth clarity.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Citrus",
    accords: ["Citrus", "Fresh", "Floral"],
    top: "Galbanum, Bergamot, Basil, Orange Blossom, Lemon, Peach",
    mid: "Lily, Lily-of-the-Valley, Jasmine, Orris Root, Rose, Ylang-Ylang",
    base: "Oakmoss, Cedar, Vetiver, Sandalwood, Musk, Amber",
    price: 49
  },
  {
    id: 18,
    name: "Dubai Gold",
    image: "Sweet gourmond.png",
    images: ["Sweet gourmond.png", "dubaig1.jpg", "dubaig2.jpg", "infoa.jpg"],
    description: "A luxurious Middle Eastern attar where rich oud meets warm amber and exotic spices, ideal for bold evening wear.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental",
    accords: ["Oud", "Amber", "Spicy"],
    top: "Saffron, Bitter Orange, Brandy",
    mid: "Cedarwood, Guaiac Wood, Juniper",
    base: "Patchouli, Sandalwood, Musk, Amber",
    price: 59
  },
 
  {
    id: 20,
    name: "Cool Tide",
    image: "fresh marine.png",
    images: ["fresh marine.png", "coolta1.jpg", "coolta2.jpg", "infoa.jpg"],
    description: "A long-lasting attar interpretation of a classic aquatic fragrance with cooling freshness and floral depth.",
    category: "Attar",
    inspiredBy: "Davidoff CoolWater",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Aquatic Fresh",
    accords: ["Fresh", "Floral", "Aquatic"],
    top: "Melon, Lotus, Lemon, Pineapple, Quince, Calone, Lily",
    mid: "Lotus, Water Lily, Lily-of-the-Valley, Jasmine, Honey, Hawthorn, Rose",
    base: "Musk, Vetiver, Raspberry, Blackberry, Violet Root, Peach, Sandalwood",
    price: 65
  },
  {
    id: 21,
    name: "Red Musk",
    image: "alln.png",
    images: ["alln.png", "redma1.jpg", "redma2.jpg", "infoa.jpg"],
    description: "A deep and sensual musky attar accented with warm spices and tobacco nuances for evening wear.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Musky",
    accords: ["Musky", "Spicy"],
    top: "Pepper",
    mid: "Cinnamon",
    base: "Tobacco, Musk",
    price: 65
  },
 
  {
    id: 23,
    name: "Chrome Breeze",
    image: "Fresh_auqatic.png",
    images: ["Fresh_auqatic.png", "chromeba1.jpg", "chromeba2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a fresh woody citrus fragrance with enhanced smoothness and longevity.",
    category: "Attar",
    inspiredBy: "Azzaro Chrome",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Fresh", "Woody", "Citrus"],
    top: "Lemon, Rosemary, Bergamot, Neroli, Pineapple",
    mid: "Jasmine, Cyclamen, Oakmoss, Coriander",
    base: "Musk, Cedar, Oakmoss, Sandalwood, Cardamom, Tonka Bean, Rosewood",
    price: 59
  },
  {
    id: 24,
    name: "Luminous Veil",
    image: "luminous_veil.jpg",
    images: ["luminous_veil.jpg", "luminousv1.jpg", "luminousv2.jpg", "info.jpg"],
    description: "A luminous floral-fruity perfume with soft powdery tones, expressing elegance, femininity, and charm.",
    category: "Perfume",
    inspiredBy: "Dior J'adore",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Fruity", "Powdery"],
    top: "Pear, Melon, Magnolia, Peach, Mandarin Orange, Bergamot",
    mid: "Jasmine, Lily-of-the-Valley, Tuberose, Freesia, Rose, Orchid, Plum, Violet",
    base: "Musk, Vanilla, Blackberry, Cedar",
    price: 65
  },
  {
    id: 25,
    name: "Luminous Veil",
    image: "norm1.png",
    images: ["norm1.png", "luminousva1.jpg", "luminousva2.jpg", "infoa.jpg"],
    description: "A refined attar rendition of a floral bouquet enriched with fruity sweetness and powdery elegance.",
    category: "Attar",
    inspiredBy: "Dior J'adore",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Fruity", "Powdery"],
    top: "Pear, Melon, Magnolia, Peach, Mandarin Orange, Bergamot",
    mid: "Jasmine, Lily-of-the-Valley, Tuberose, Freesia, Rose, Orchid, Plum, Violet",
    base: "Musk, Vanilla, Blackberry, Cedar",
    price: 89
  },
    {
    id: 26,
    name: "Golden Flora",
    image: "female floral.png",
    images: ["female floral.png", "goldenfa1.jpg", "goldenfa2.jpg", "infoa.jpg"],
    description: "A bright and elegant floral-fruity attar with fresh citrus nuances, radiating youthful femininity and charm.",
    category: "Attar",
    inspiredBy: "Gucci Flora",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Fruity", "Citrus"],
    top: "Peony, Citrus Fruits, Mandarin Orange",
    mid: "Osmanthus, Rose",
    base: "Sandalwood, Patchouli, Pink Pepper",
    price: 65
  },
  {
    id: 27,
    name: "Cool Essence",
    image: "fresh marine.png",
    images: ["fresh marine.png", "coolea1.jpg", "coolea2.jpg", "infoa.jpg"],
    description: "A sporty and energetic fresh aromatic fragrance inspired by outdoor vitality and aquatic freshness.",
    category: "Attar",
    inspiredBy: "Polo Sports",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aromatic",
    accords: ["Fresh", "Aromatic", "Citrus"],
    top: "Mint, Aldehydes, Lavender, Bergamot, Mandarin Orange, Lemon, Artemisia, Neroli",
    mid: "Seagrass, Jasmine, Ginger, Geranium, Rose, Cyclamen, Brazilian Rosewood",
    base: "Musk, Sandalwood, Cedar, Guaiac Wood, Amber",
    price: 89
  },
  {
    id: 28,
    name: "Majmua",
    image: "norm2.png",
    images: ["norm2.png", "majmuaa1.jpg", "majmuaa2.jpg", "infoa.jpg"],
    description: "A classic traditional attar blending floral, herbal, and musky tones, deeply rooted in Indo-Arabic perfumery.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Oriental Floral",
    accords: ["Floral", "Herbal", "Musky"],
    top: "Kewda (Screw Pine), Green Notes",
    mid: "Rose (Ruh Gulab), Hina (Henna)",
    base: "Vetiver (Khus), Sandalwood",
    price: 65
  },
  {
    id: 29,
    name: "Majmua Premium",
    image: "prem5.png",
    images: ["prem5.png", "majmuapap1.jpg", "majmuapap2.jpg", "infoa.jpg"],
    description: "A richer and more refined version of Majmua with enhanced depth, smoothness, and lasting power.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Oriental Floral",
    accords: ["Floral", "Herbal", "Musky"],
    top: "Kewda (Screw Pine), Green Notes",
    mid: "Rose (Ruh Gulab), Hina (Henna)",
    base: "Vetiver (Khus), Sandalwood",
    price: 899
  },
  {
    id: 30,
    name: "Mukhallat",
    image: "smoky, oudy, spicy.png",
    images: ["smoky, oudy, spicy.png", "mukhallata1.jpg", "mukhallata2.jpg", "infoa.jpg"],
    description: "A bold oriental attar combining oud, amber, and spices for a warm and luxurious evening presence.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental",
    accords: ["Oriental", "Amber", "Spicy"],
    top: "Oud (Agarwood)",
    mid: "Saffron",
    base: "Musk, Amber, Woody Notes",
    price: 65
  },
  {
    id: 31,
    name: "Mukhallat Premium",
    image: "all.png",
    images: ["all.png", "mukhallatpa1.jpg", "mukhallatpa2.jpg", "infoa.jpg"],
    description: "A premium interpretation of Mukhallat offering deeper oud richness and smoother amber warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental",
    accords: ["Oriental", "Amber", "Spicy"],
    top: "Oud (Agarwood)",
    mid: "Saffron",
    base: "Musk, Amber, Woody Notes",
    price: 999
  },
  {
    id: 32,
    name: "Ameer Al OUD",
    image: "smoky, oudy, spicy.png",
    images: ["smoky, oudy, spicy.png", "ameeraa1.jpg", "ameeraa2.jpg", "infoa.jpg"],
    description: "A sweet woody oud fragrance with vanilla warmth, balancing richness and smooth gourmand undertones.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Sweet", "Amber"],
    top: "Oud, Woody Notes",
    mid: "Vanilla, Sugar",
    base: "Agarwood (Oud), Sandalwood, Herbal Notes",
    price: 75
  },
  {
    id: 33,
    name: "Ameer Al OUD Premium",
    image: "oudyspicyfresh.png",
    images: ["oudyspicyfresh.png", "ameerapa1.jpg", "ameerapa2.jpg", "infoa.jpg"],
    description: "A premium and smoother oud blend with intensified sweetness and long-lasting woody depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Sweet", "Amber"],
    top: "Oud, Woody Notes",
    mid: "Vanilla, Sugar",
    base: "Agarwood (Oud), Sandalwood, Herbal Notes",
    price: 249
  },
  {
    id: 34,
    name: "Shay Oud",
    image: "Smoky.png",
    images: ["Smoky.png", "shayoa1.jpg", "shayoa2.jpg", "infoa.jpg"],
    description: "A warm oriental oud fragrance enriched with honeyed sweetness and smoky incense accents.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Oriental", "Honey"],
    top: "Frankincense (Luban)",
    mid: "Honey",
    base: "Agarwood (Oud), Musk",
    price: 85
  },
  {
    id: 35,
    name: "Shay Oud Premium",
    image: "Smoky.png",
    images: ["Smoky.png", "shayopa1.jpg", "shayopa2.jpg", "infoa.jpg"],
    description: "A deeper and more refined version of Shay Oud with enhanced honeyed warmth and resinous oud.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Oriental", "Honey"],
    top: "Frankincense (Luban)",
    mid: "Honey",
    base: "Agarwood (Oud), Musk",
    price: 239
  },
  {
    id: 36,
    name: "Jannatul Ferdous",
    image: "norm7.png",
    images: ["norm7.png", "jannatulfa1.jpg", "jannatulfa2.jpg", "infoa.jpg"],
    description: "A fresh herbal-floral attar with green and spicy undertones, traditionally worn for daytime serenity.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Herbal Floral",
    accords: ["Herbal", "Floral", "Spicy"],
    top: "Lotus, Gardenia, Green Notes",
    mid: "Rose, Grass",
    base: "Herbal Notes, Woody Notes",
    price: 70
  },
  {
    id: 37,
    name: "Zam Zam",
    image: "norm6.png",
    images: ["norm6.png", "zamza1.jpg", "zamza2.jpg", "infoa.jpg"],
    description: "A clean and uplifting fresh aromatic attar with watery florals and gentle musky warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aromatic",
    accords: ["Fresh", "Aromatic"],
    top: "Bergamot, Mint, Watercress",
    mid: "Lilies, Iris, Jasmine",
    base: "Woody Notes, Musk, Apricot",
    price: 65
  },
  {
    id: 38,
    name: "Magnet",
    image: "Smoky.png",
    images: ["Smoky.png", "magneta1.jpg", "magneta2.jpg", "infoa.jpg"],
    description: "A complex floral-woody fragrance with fruity sweetness and resinous warmth, bold yet elegant.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Floral",
    accords: ["Floral", "Woody", "Mossy"],
    top: "Red Berries, Black Currant, Cassia, Litchi, Pineapple, Melon",
    mid: "Green Leaves, Basil, Almond Blossom, Iris, Freesia, Jasmine, Rose",
    base: "Caramel, Vanilla, Patchouli, Benzoin, Musk, Sandalwood, Amber, Vetiver",
    price: 49
  },
  {
    id: 39,
    name: "Aqua Wave",
    image: "fresh marine.png",
    images: ["fresh marine.png", "aquawa1.jpg", "aquawa2.jpg", "infoa.jpg"],
    description: "A marine-fresh fragrance inspired by ocean air, blending citrus brightness with salty aquatic notes.",
    category: "Attar",
    inspiredBy: "Aqua De Gio",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Marine Fresh",
    accords: ["Fresh", "Marine", "Citrus"],
    top: "Lime, Lemon, Bergamot, Jasmine, Orange, Mandarin Orange, Neroli",
    mid: "Sea Notes, Jasmine, Calone, Rosemary, Peach, Freesia, Cyclamen",
    base: "White Musk, Cedar, Oakmoss, Patchouli, Amber",
    price: 65
  },
  {
    id: 40,
    name: "Blue Wave",
    image: "Fresh_auqatic.png",
    images: ["Fresh_auqatic.png", "bluewa1.jpg", "bluewa2.jpg", "infoa.jpg"],
    description: "A light and refreshing citrus-aquatic attar designed for everyday summer freshness.",
    category: "Attar",
    inspiredBy: "",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Citrus",
    accords: ["Fresh", "Citrus", "Fruity"],
    top: "Bergamot, Mandarin Orange",
    mid: "Aquatic Accords, Lavender",
    base: "Amber, Woody Notes, Musk",
    price: 59
  },
   {
    id: 41,
    name: "Blue Water",
    image: "norm6.png",
    images: ["norm6.png", "bluewa1.jpg", "bluewa2.jpg", "infoa.jpg"],
    description: "A clean and refreshing aromatic aquatic attar with marine freshness and woody undertones.",
    category: "Attar",
    inspiredBy: "",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aromatic",
    accords: ["Fresh", "Aromatic"],
    top: "Sea Water, Citrus, Green Notes",
    mid: "Neroli, Geranium",
    base: "Oakmoss, Cedar",
    price: 59
  },
  {
    id: 42,
    name: "Velour Si",
    image: "female floral.png",
    images: ["female floral.png", "veloursa1.jpg", "veloursa2.jpg", "infoa.jpg"],
    description: "A sophisticated fruity-floral fragrance with warm vanilla undertones, elegant and feminine.",
    category: "Attar",
    inspiredBy: "Armani Si",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Floral Fruity",
    accords: ["Floral", "Fruity", "Warm"],
    top: "Cassis (Blackcurrant Syrup)",
    mid: "May Rose, Freesia",
    base: "Vanilla, Patchouli, Ambroxan, Woody Notes",
    price: 59
  },
  // {
  //   id: 43,
  //   name: "Captain’s Ember",
  //   image: "captainse.jpg",
  //   images: ["captainse.jpg", "captainse1.jpg", "captainse2.jpg", "info.jpg"],
  //   description: "A bold and seductive amber-woody fragrance with sweet and spicy depth for evening wear.",
  //   category: "Perfume",
  //   inspiredBy: "Le Male Elixir",
  //   gender: "Male",
  //   season: "Autumn-Winter",
  //   time: "Night",
  //   family: "Amber Woody",
  //   accords: ["Sweet", "Amber", "Woody"],
  //   top: "Lavender, Mint",
  //   mid: "Vanilla, Benzoin",
  //   base: "Honey, Tonka Bean, Tobacco",
  //   price: 89
  // },
  {
    id: 44,
    name: "Captain’s Ember",
    image: "norm5.png",
    images: ["norm5.png", "captainsea1.jpg", "captainsea2.jpg", "infoa.jpg"],
    description: "A concentrated attar version delivering warm amber sweetness and woody sensuality.",
    category: "Attar",
    inspiredBy: "Le Male Elixir",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Woody",
    accords: ["Sweet", "Amber", "Woody"],
    top: "Lavender, Mint",
    mid: "Vanilla, Benzoin",
    base: "Honey, Tonka Bean, Tobacco",
    price: 65
  },
  {
    id: 45,
    name: "Sabaya",
    image: "female floral.png",
    images: ["female floral.png", "sabyaa1.jpg", "sabyaa2.jpg", "infoa.jpg"],
    description: "A light and airy floral attar with herbal freshness, ideal for warm daytime wear.",
    category: "Attar",
    inspiredBy: "",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Herbal"],
    top: "Citrus",
    mid: "Green Notes",
    base: "Rose",
    price: 59
  },
  {
    id: 46,
    name: "Purple OUD",
    image: "norm4.png",
    images: ["norm4.png", "purpleoa1.jpg", "purpleoa2.jpg", "infoa.jpg"],
    description: "A spicy oriental oud fragrance with saffron warmth and woody depth for night-time wear.",
    category: "Attar",
    inspiredBy: "Dior Purple Oud",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Oriental", "Woody", "Spicy"],
    top: "Pink Pepper, Orange",
    mid: "Saffron",
    base: "Agarwood (Oud)",
    price: 70
  },
  {
    id: 47,
    name: "Pulse Royale",
    image: "norm6.png",
    images: ["norm6.png", "pulsera1.jpg", "pulsera2.jpg", "infoa.jpg"],
    description: "A modern marine-sweet fragrance with spicy tobacco undertones, energetic and youthful.",
    category: "Attar",
    inspiredBy: "CR-7",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Sweet",
    accords: ["Sweet", "Marine", "Sweet"],
    top: "Lavender, Cardamom, Artemisia, Bergamot",
    mid: "Tobacco, Cinnamon, Cedar, Iris",
    base: "Vanilla, Musk, Sandalwood, Amber",
    price: 65
  },
  {
    id: 48,
    name: "Invictus",
    image: "fresh marine.png",
    images: ["fresh marine.png", "invictusa1.jpg", "invictusa2.jpg", "infoa.jpg"],
    description: "A powerful fresh-marine fragrance with citrus brightness and woody amber depth.",
    category: "Attar",
    inspiredBy: "Paco Rabanne Invictus",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Marine Fresh",
    accords: ["Citrus", "Marine", "Aromatic"],
    top: "Sea Notes, Grapefruit, Mandarin Orange",
    mid: "Bay Leaf, Jasmine",
    base: "Ambergris, Guaiac Wood, Oakmoss, Patchouli",
    price: 65
  },
  {
    id: 49,
    name: "Aseel",
    image: "norm1.png",
    images: ["norm1.png", "aseela1.jpg", "aseela2.jpg", "infoa.jpg"],
    description: "A balanced woody-floral attar with herbal nuances and soft musky depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Floral",
    accords: ["Woody", "Floral", "Herbal"],
    top: "Red Rose, Saffron",
    mid: "Sandalwood, Mint",
    base: "Agarwood (Oud), Musk",
    price: 65
  },
  {
    id: 50,
    name: "Fasli Gulab",
    image: "fasli gulab.png",
    images: ["fasli gulab.png", "fasliga1.jpg", "fasliga2.jpg", "infoa.jpg"],
    description: "A soft and powdery rose attar capturing the freshness of blooming garden roses.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Floral", "Powdery"],
    top: "Rose",
    mid: "",
    base: "",
    price: 65
  },
  {
    id: 51,
    name: "Aventus",
    image: "creed aventus.png",
    images: ["creed aventus.png", "aventusa1.jpg", "aventusa2.jpg", "infoa.jpg"],
    description: "A bold fruity-chypre fragrance with smoky woods and fresh pineapple character.",
    category: "Attar",
    inspiredBy: "Creed Aventus",
    gender: "Male",
    season: "All seasons",
    time: "Day/Night",
    family: "Chypre Fruity",
    accords: ["Fruity-Chypre", "Woody"],
    top: "Pineapple, Bergamot, Blackcurrant, Apple",
    mid: "Birch, Patchouli, Moroccan Jasmine, Rose",
    base: "Musk, Oakmoss, Ambergris, Vanille",
    price: 85
  },
  {
    id: 52,
    name: "Golden Blush",
    image: "female floral.png",
    images: ["female floral.png", "goldenba1.jpg", "goldenba2.jpg", "infoa.jpg"],
    description: "A delicate floral gourmand fragrance with creamy sweetness and soft freshness.",
    category: "Attar",
    inspiredBy: "Carolina Herrrera Good Girl Blush",
    gender: "Female",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral Gourmand",
    accords: ["Floral", "Gourmand", "Fresh"],
    top: "Bergamot, Bitter Almond",
    mid: "Peony, Ylang-Ylang",
    base: "Vanilla, Coumarin",
    price: 65
  },
  
  {
    id: 54,
    name: "Fresh Horizon",
    image: "fresh marine.png",
    images: ["fresh marine.png", "freshha1.jpg", "freshha2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version delivering sweet woody warmth with fresh aromatic highlights.",
    category: "Attar",
    inspiredBy: "Versace Eros",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Oriental", "Sweet"],
    top: "Mint, Green Apple, Lemon",
    mid: "Tonka Bean, Ambroxan, Geranium",
    base: "Vanilla, Cedar, Vetiver, Oakmoss",
    price: 65
  },
  
  {
    id: 56,
    name: "Velvet Night",
    image: "Sweet gourmond.png",
    images: ["Sweet gourmond.png", "velvetna1.jpg", "velvetna2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a rich gourmand-oriental scent with coffee sweetness and creamy vanilla depth.",
    category: "Attar",
    inspiredBy: "YSL Black Opium",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Gourmand", "Oriental", "Sweet"],
    top: "Pear, Pink Pepper, Orange Blossom",
    mid: "Coffee, Jasmine, Bitter Almond, Licorice",
    base: "Vanilla, Patchouli, Cedar, Cashmere Wood",
    price: 65
  },
  {
    id: 57,
    name: "Titanium",
    image: "Titanium.png",
    images: ["Titanium.png", "titanium1.jpg", "titanium2.jpg", "info.jpg"],
    description: "A fresh aromatic-fruity fragrance offering a clean, energetic profile suitable for everyday wear.",
    category: "Perfume",
    inspiredBy: "Titanium Ajmal",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Fresh",
    accords: ["Aromatic", "Fruity"],
    top: "Citrus, Fruity Notes",
    mid: "Fresh Spicy Notes",
    base: "Woody Notes, Musk",
    price: 65
  },
  {
    id: 58,
    name: "Titanium",
    image: "fresh marine.png",
    images: ["fresh marine.png", "titaniuma1.jpg", "titaniuma2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version of a crisp aromatic fragrance with fruity freshness and woody warmth.",
    category: "Attar",
    inspiredBy: "Titanium Ajmal",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Aromatic Fresh",
    accords: ["Aromatic", "Fruity"],
    top: "Citrus, Fruity Notes",
    mid: "Fresh Spicy Notes",
    base: "Woody Notes, Musk",
    price: 89
  },
  {
    id: 59,
    name: "White OUD",
    image: "norm2.png",
    images: ["norm2.png", "whiteoa1.jpg", "whiteoa2.jpg", "infoa.jpg"],
    description: "A refined oud fragrance softened by fresh florals and subtle tobacco warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Floral",
    accords: ["Fresh", "Floral"],
    top: "Artemisia, Lemon, Orange",
    mid: "Freesia, Patchouli, Black Currant",
    base: "Tobacco, Amber, Musk",
    price: 75
  },
 

  {
    id: 61,
    name: "Most Wanted",
    image: "norm2.png",
    images: ["norm2.png", "mostwa1.jpg", "mostwa2.jpg", "infoa.jpg"],
    description: "A concentrated attar interpretation delivering intense sweetness and woody amber richness.",
    category: "Attar",
    inspiredBy: "AZ The Most Wanted",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Woody",
    accords: ["Amber", "Woody", "Sweet"],
    top: "Cardamom",
    mid: "Toffee",
    base: "Amberwood",
    price: 75
  },
 
  {
    id: 63,
    name: "BLU Ember",
    image: "Fresh_auqatic.png",
    images: ["Fresh_auqatic.png", "bluea1.jpg", "bluea2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version offering aquatic freshness balanced with aromatic warmth.",
    category: "Attar",
    inspiredBy: "Ajmal BLU",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Aquatic",
    accords: ["Fresh", "Aquatic", "Aromatic"],
    top: "Watermelon, Bergamot, Lavender",
    mid: "Lotus, Jasmine",
    base: "Musk, Amber, Sandalwood",
    price: 65
  },
 
  {
    id: 65,
    name: "Caramel OUD",
    image: "sweet chocolate gourmond.png",
    images: ["sweet chocolate gourmond.png", "carameloa1.jpg", "carameloa2.jpg", "infoa.jpg"],
    description: "A rich attar version offering intense caramel sweetness balanced with smoky oud depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Gourmand Woody",
    accords: ["Gourmand", "Woody"],
    top: "Chocolate, Honey",
    mid: "Rose, Oud, Amber",
    base: "Vanilla, Powdery Notes",
    price: 65
  },
  {
    id: 66,
    name: "Shanaya",
    image: "norm4.png",
    images: ["norm4.png", "shanaya1.jpg", "shanaya2.jpg", "info.jpg"],
    description: "A graceful woody-floral fragrance accented with amber warmth and soft sweetness.",
    category: "Attar",
    inspiredBy: "",
    gender: "Female",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Floral",
    accords: ["Woody", "Floral", "Amber"],
    top: "Rose, Saffron, Pimento",
    mid: "Agarwood (Oud), Caramel, Floral Notes",
    base: "Resins, Amber, Musk",
    price: 75
  },
  {
    id: 67,
    name: "Fresh Impact",
    image: "fresh marine.png",
    images: ["freshia.jpg", "freshia1.jpg", "freshia2.jpg", "infoa.jpg"],
    description: "A vibrant citrus-spicy fragrance with green freshness and refined woody depth.",
    category: "Attar",
    inspiredBy: "LV Imagination",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Spicy",
    accords: ["Citrus", "Fresh-Spicy", "Green"],
    top: "Citron, Calabrian Bergamot, Orange",
    mid: "Ginger, Tunisian Neroli, Cinnamon",
    base: "Tea, Ambroxan, Guaiac Wood, Olibanum",
    price: 65
  },
  // {
  //   id: 68,
  //   name: "Azure Coast",
  //   image: "azurec.jpg",
  //   images: ["azurec.jpg", "azurec1.jpg", "azurec2.jpg", "info.jpg"],
  //   description: "A sparkling citrus aquatic fragrance capturing the freshness of sunlit coastal air.",
  //   category: "Perfume",
  //   inspiredBy: "LV Afternoon swim",
  //   gender: "Male",
  //   season: "Spring-Summer",
  //   time: "Day",
  //   family: "Citrus Fresh",
  //   accords: ["Citrus", "Fresh Spicy", "Amber"],
  //   top: "Mandarin Orange",
  //   mid: "Bergamot",
  //   base: "Ambergris, Ginger",
  //   price: 129
  // },
  {
    id: 69,
    name: "Azure Coast",
    image: "fresh marine.png",
    images: ["fresh marine.png", "azureca1.jpg", "azureca2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version delivering bright citrus freshness with subtle amber warmth.",
    category: "Attar",
    inspiredBy: "LV Afternoon swim",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Citrus Fresh",
    accords: ["Citrus", "Fresh Spicy", "Amber"],
    top: "Mandarin Orange",
    mid: "Bergamot",
    base: "Ambergris, Ginger",
    price: 99
  },
  {
    id: 70,
    name: "BR 540",
    image: "BR 540.png",
    images: ["BR 540.png", "br540.jpg", "br5402.jpg", "info.jpg"],
    description: "A luxurious ambery fragrance with saffron warmth, airy sweetness, and radiant depth.",
    category: "Perfume",
    inspiredBy: "MFK Baccarat Rouge 540",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Amber Woody",
    accords: ["Amber", "Sweet", "Woody"],
    top: "Saffron, Jasmine",
    mid: "Amberwood, Ambergris",
    base: "Fir Resin, Cedar",
    price: 89
  },
  {
    id: 71,
    name: "BR 540",
    image: "bSmoky.pngr540a.jpg",
    images: ["Smoky.png", "br540a1.jpg", "br540a2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a radiant ambery fragrance with airy sweetness and luxurious warmth.",
    category: "Attar",
    inspiredBy: "MFK Baccarat Rouge 540",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Amber Woody",
    accords: ["Amber", "Sweet", "Woody"],
    top: "Saffron, Jasmine",
    mid: "Amberwood, Ambergris",
    base: "Fir Resin, Cedar",
    price: 65
  },
  // {
  //   id: 72,
  //   name: "Qahwa",
  //   image: "qahwa.jpg",
  //   images: ["qahwa.jpg", "qahwa1.jpg", "qahwa2.jpg", "info.jpg"],
  //   description: "A rich and spicy coffee-infused fragrance with gourmand sweetness and warm oriental depth.",
  //   category: "Perfume",
  //   inspiredBy: "Khamra Qahwa",
  //   gender: "Unisex",
  //   season: "Autumn-Winter",
  //   time: "Night",
  //   family: "Oriental Gourmand",
  //   accords: ["Spicy", "Coffee", "Sweet"],
  //   top: "Ginger, Cinnamon, Cardamom",
  //   mid: "Praline, Candied Fruits",
  //   base: "Coffee, Tonka Bean, Vanilla",
  //   price: 99
  // },
  {
    id: 73,
    name: "Qahwa",
    image: "Sweet gourmond.png",
    images: ["Sweet gourmond.png", "qahwaa1.jpg", "qahwaa2.jpg", "infoa.jpg"],
    description: "A long-lasting attar rendition delivering bold coffee warmth blended with sweet spices.",
    category: "Attar",
    inspiredBy: "Khamra Qahwa",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Spicy", "Coffee", "Sweet"],
    top: "Ginger, Cinnamon, Cardamom",
    mid: "Praline, Candied Fruits",
    base: "Coffee, Tonka Bean, Vanilla",
    price: 79
  },
  
  {
    id: 75,
    name: "Obsidian OUD",
    image: "Smoky.png",
    images: ["Smoky.png", "obsidianoa1.jpg", "obsidianoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar version offering intense fruity sweetness layered over smoky oud.",
    category: "Attar",
    inspiredBy: "Oud maracuja",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Fruity Woody",
    accords: ["Fruity-Chypre", "Woody"],
    top: "Passionfruit, Saffron, Turkish Rose",
    mid: "Oud, Patchouli, Benzoin",
    base: "Leather, Amber, Vanilla",
    price: 79
  },
  {
    id: 76,
    name: "Dark Rebel",
    image: "dark rebel.png",
    images: ["dark rebel.png", "darkra1.jpg", "darkra2.jpg", "infoa.jpg"],
    description: "A dark woody-spicy fragrance with smoky oud and warm amber undertones.",
    category: "Attar",
    inspiredBy: "TF OUD wood",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Spicy", "Oriental"],
    top: "Cardamom, Sichuan Pepper",
    mid: "Vanilla",
    base: "Tonka Bean, Oud, Vetiver, Amber",
    price: 89
  },
  {
    id: 77,
    name: "Woody OUD",
    image: "Smoky.png",
    images: ["Smoky.png", "woodyoa1.jpg", "woodyoa2.jpg", "infoa.jpg"],
    description: "A powerful woody-oriental attar with spicy warmth and deep resinous oud character.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Spicy", "Oriental"],
    top: "Cardamom, Sichuan Pepper",
    mid: "Vanilla",
    base: "Tonka Bean, Oud, Vetiver, Amber",
    price: 279
  },
  {
    id: 78,
    name: "Musk Abiyad",
    image: "muskaa.jpg",
    images: ["muskaa.jpg", "muskaa1.jpg", "muskaa2.jpg", "infoa.jpg"],
    description: "A soft and clean white musk fragrance with powdery floral nuances for everyday wear.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky",
    accords: ["Musky", "Powdery", "Floral"],
    top: "Rose, White Musk",
    mid: "Balsamic, Powdery Notes",
    base: "Musk, Sandalwood",
    price: 79
  },
  {
    id: 79,
    name: "Midnight",
    image: "midnighta.jpg",
    images: ["midnighta.jpg", "midnighta1.jpg", "midnighta2.jpg", "infoa.jpg"],
    description: "A fresh spicy-woody fragrance with citrus brightness and aromatic warmth for evening wear.",
    category: "Attar",
    inspiredBy: "",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Fresh Spicy", "Citrus"],
    top: "Bergamot, Lavender",
    mid: "Geranium, Orange Blossom",
    base: "Patchouli, Woody Notes",
    price: 59
  },
  {
    id: 80,
    name: "Musk Safi",
    image: "musksa.jpg",
    images: ["musksa.jpg", "musksa1.jpg", "musksa2.jpg", "infoa.jpg"],
    description: "A clean musky fragrance balanced with soft florals and smooth woody undertones.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky Floral",
    accords: ["Musky", "Woody", "Floral"],
    top: "Lily of the Valley",
    mid: "White Musk",
    base: "Sandalwood, Amber",
    price: 79
  },
  {
    id: 81,
    name: "Eternal Sauvage",
    image: "eternalsa.jpg",
    images: ["eternalsa.jpg", "eternalsa1.jpg", "eternalsa2.jpg", "infoa.jpg"],
    description: "A fresh spicy fragrance with aromatic herbs and ambroxan depth, powerful and versatile.",
    category: "Attar",
    inspiredBy: "Dior Sauvage",
    gender: "Male",
    season: "All seasons",
    time: "Day/Night",
    family: "Fresh Spicy",
    accords: ["Fresh", "Spicy-Oriental"],
    top: "Calabrian Bergamot, Pepper",
    mid: "Sichuan Pepper, Lavender, Vetiver",
    base: "Ambroxan, Cedar, Labdanum",
    price: 65
  },
  {
    id: 82,
    name: "Dahnal OUD",
    image: "dahnaloa.jpg",
    images: ["dahnaloa.jpg", "dahnaloa1.jpg", "dahnaloa2.jpg", "infoa.jpg"],
    description: "A raw and powerful oud attar with honeyed warmth and deep woody intensity.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Honey", "Spicy"],
    top: "Oud",
    mid: "",
    base: "",
    price: 99
  },
  {
    id: 83,
    name: "Eternal White",
    image: "Eternal White.png",
    images: ["Eternal White.png", "eternalw1.jpg", "eternalw2.jpg", "info.jpg"],
    description: "A clean citrus-woody fragrance with aromatic freshness and smooth leather undertones.",
    category: "Perfume",
    inspiredBy: "Lacoste White",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Citrus", "Woody", "Aromatic"],
    top: "Grapefruit, Rosemary, Cardamom",
    mid: "Ylang-Ylang, Tuberose",
    base: "Suede, Cedar, Leather, Vetiver",
    price: 65
  },
  {
    id: 84,
    name: "Eternal White",
    image: "eternalwa.jpg",
    images: ["eternalwa.jpg", "eternalwa1.jpg", "eternalwa2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version delivering crisp citrus freshness and woody elegance.",
    category: "Attar",
    inspiredBy: "Lacoste White",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Citrus", "Woody", "Aromatic"],
    top: "Grapefruit, Rosemary, Cardamom",
    mid: "Ylang-Ylang, Tuberose",
    base: "Suede, Cedar, Leather, Vetiver",
    price: 89
  },
  {
    id: 85,
    name: "Tao Mist",
    image: "taoma.jpg",
    images: ["taoma.jpg", "taoma1.jpg", "taoma2.jpg", "infoa.jpg"],
    description: "A serene woody-earthy fragrance centered around creamy sandalwood and soft spice.",
    category: "Attar",
    inspiredBy: "Tam Dao",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Day",
    family: "Woody Earthy",
    accords: ["Woody", "Earthy"],
    top: "Cypress, Myrtle, Rose",
    mid: "Sandalwood, Cedar",
    base: "Rosewood, Spices, Amber, White Musk",
    price: 85
  },
  {
    id: 86,
    name: "Urban Icon",
    image: "urbania.jpg",
    images: ["urbania.jpg", "urbania1.jpg", "urbania2.jpg", "infoa.jpg"],
    description: "A refined woody-aromatic fragrance with spicy freshness and smooth leather undertones, modern and confident.",
    category: "Attar",
    inspiredBy: "Dunhil Icon Grey",
    gender: "Male",
    season: "All seasons",
    time: "Day",
    family: "Woody Aromatic",
    accords: ["Woody", "Aromatic", "Spicy"],
    top: "Neroli, Bergamot, Black Pepper",
    mid: "Lavender, Cardamom, Juniper Berries",
    base: "Vetiver, Oakmoss, Leather, Oud",
    price: 85
  },
  {
    id: 87,
    name: "Intense Suede",
    image: "intensesa.jpg",
    images: ["intensesa.jpg", "intensesa1.jpg", "intensesa2.jpg", "infoa.jpg"],
    description: "A rich vanilla-amber fragrance with suede softness and warm spicy accents for intense evening wear.",
    category: "Attar",
    inspiredBy: "Armani SWY intensely",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Vanilla",
    accords: ["Vanilla", "Sweet", "Amber"],
    top: "Pink Pepper, Juniper, Violet",
    mid: "Toffee, Cinnamon, Lavender, Sage",
    base: "Vanilla, Amber, Tonka Bean, Suede",
    price: 75
  },
  
  {
    id: 89,
    name: "Aurum",
    image: "auruma.jpg",
    images: ["auruma.jpg", "auruma1.jpg", "auruma2.jpg", "infoa.jpg"],
    description: "A concentrated attar version offering creamy white florals with soft fruity sweetness.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Floral, Fresh",
    accords: ["White Floral", "Fruity", "Powdery"],
    top: "Raspberry, Lemon",
    mid: "Orange Blossom, Gardenia, Jasmine",
    base: "Vanilla, Amber, Musk",
    price: 129
  },
  {
    id: 90,
    name: "Blue OUD",
    image: "Blue OUD.png",
    images: ["Blue OUD.png", "blueo1.jpg", "blueo2.jpg", "info.jpg"],
    description: "A bold oud-leather fragrance with smoky depth and earthy patchouli richness.",
    category: "Perfume",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Oud", "Leather", "Patchouli"],
    top: "Blue Lily, Oud",
    mid: "Patchouli, Leather",
    base: "Amber, Tobacco",
    price: 175
  },
    {
    id: 91,
    name: "Blue OUD",
    image: "blueoa.jpg",
    images: ["blueoa.jpg", "blueoa1.jpg", "blueoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar delivering intense oud-leather richness with smoky warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Oud", "Leather", "Patchouli"],
    top: "Blue Lily, Oud",
    mid: "Patchouli, Leather",
    base: "Amber, Tobacco",
    price: 175
  },
  {
    id: 92,
    name: "Musk Rijali",
    image: "muskr.jpg",
    images: ["muskr.jpg", "muskr1.jpg", "muskr2.jpg", "info.jpg"],
    description: "A refined musky fragrance with subtle sweetness and gentle floral warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky",
    accords: ["Musky", "Subtle Sweet", "Floral"],
    top: "Musk, Bergamot",
    mid: "Jasmine, Saffron",
    base: "Oud, Amber, Vanilla",
    price: 175
  },
  {
    id: 93,
    name: "Musk Rijali Premium",
    image: "muskrpa.jpg",
    images: ["muskrpa.jpg", "muskrpa1.jpg", "muskrpa2.jpg", "infoa.jpg"],
    description: "A premium musky attar with enhanced smoothness, sweetness, and long-lasting warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky",
    accords: ["Musky", "Subtle Sweet", "Floral"],
    top: "Musk, Bergamot",
    mid: "Jasmine, Saffron",
    base: "Oud, Amber, Vanilla",
    price: 289
  },
  {
    id: 94,
    name: "OUD Al Shams",
    image: "oudasa.jpg",
    images: ["oudasa.jpg", "oudasa1.jpg", "oudasa2.jpg", "infoa.jpg"],
    description: "A warm spicy-vanilla oud fragrance with amber richness and smooth woody depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Spicy",
    accords: ["Spicy", "Vanilla", "Amber"],
    top: "Rosemary, Spicy Notes",
    mid: "Amber, Blackberry",
    base: "Cashmere Wood, Vanilla",
    price: 175
  },
  {
    id: 95,
    name: "OUD Rijali",
    image: "oudra.jpg",
    images: ["oudra.jpg", "oudra1.jpg", "oudra2.jpg", "infoa.jpg"],
    description: "A rich woody-spicy oud fragrance with subtle sweetness and earthy depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Subtle Sweet", "Spicy"],
    top: "Saffron, Herbal Accents",
    mid: "Patchouli, Rose, Amber",
    base: "Oud, Sandalwood, Musk",
    price: 175
  },
  {
    id: 96,
    name: "Musk Gazali",
    image: "muskg.jpg",
    images: ["muskg.jpg", "muskg1.jpg", "muskg2.jpg", "info.jpg"],
    description: "A deep musky fragrance with warm spices, woody richness, and gourmand chocolate nuances.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Musky Spicy",
    accords: ["Musky", "Woody", "Warm Spicy"],
    top: "Caraway, Anise",
    mid: "Musk",
    base: "Woody Notes, Spicy Notes, Vanilla, Chocolate",
    price: 175
  },
  {
    id: 97,
    name: "Black OUD",
    image: "blackoa.jpg",
    images: ["blackoa.jpg", "blackoa1.jpg", "blackoa2.jpg", "infoa.jpg"],
    description: "A smoky woody oud fragrance with leathery depth and earthy warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Smoky"],
    top: "Lemon, Mandarin, Oud, Saffron",
    mid: "Rose, Patchouli",
    base: "Leather, Sandalwood, White Musk, Guaiacwood",
    price: 175
  },
  {
    id: 98,
    name: "Mukhallat OUD",
    image: "mukhallatoa.jpg",
    images: ["mukhallatoa.jpg", "mukhallatoa1.jpg", "mukhallatoa2.jpg", "infoa.jpg"],
    description: "A floral-woody oud blend with spicy warmth and smooth musky undertones.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Floral",
    accords: ["Floral", "Woody", "Spicy"],
    top: "Floral Notes, Spicy Notes",
    mid: "Fruity Notes, Musk",
    base: "Musk, Woody Notes",
    price: 249
  },
  {
    id: 99,
    name: "Mukhallat Rashid",
    image: "mukhallatra.jpg",
    images: ["mukhallatra.jpg", "mukhallatra1.jpg", "mukhallatra2.jpg", "infoa.jpg"],
    description: "A complex leathery-woody fragrance with floral spices and earthy depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Leathery", "Woody", "Spicy Floral"],
    top: "Saffron, Clove, Sage",
    mid: "Rose, Geranium, Henna",
    base: "Oud, Vetiver, Soil Tincture, Patchouli",
    price: 249
  },
  {
    id: 100,
    name: "Oud Mubakhar",
    image: "oudma.jpg",
    images: ["oudma.jpg", "oudma1.jpg", "oudma2.jpg", "infoa.jpg"],
    description: "A warm spicy-woody fragrance with floral accents and smooth resinous warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Warm Spicy", "Woody", "Floral"],
    top: "Saffron, Bergamot",
    mid: "Rose, Geranium, Violet",
    base: "Musk, Sandalwood, Tonka Bean, Patchouli",
    price: 249
  },
  {
    id: 101,
    name: "Malik Al Musk",
    image: "malikama.jpg",
    images: ["malikama.jpg", "malikama1.jpg", "malikama2.jpg", "infoa.jpg"],
    description: "A soft and elegant musky fragrance with powdery florals and a clean, comforting character.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky Floral",
    accords: ["Musky", "Floral", "Powdery"],
    top: "Green Apple, Lemon, Violet Leaf",
    mid: "Bulgarian Rose, Jasmine, Geranium",
    base: "Musk, Sandalwood",
    price: 249
  },
  {
    id: 102,
    name: "Mukhallat Maliky",
    image: "mukhallatma.jpg",
    images: ["mukhallatma.jpg", "mukhallatma1.jpg", "mukhallatma2.jpg", "infoa.jpg"],
    description: "A warm woody-amber fragrance enriched with spices and smooth oriental depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Amber",
    accords: ["Woody", "Warm Spicy", "Amber"],
    top: "Warm Spices, Soft Florals",
    mid: "Oud, Amber, Floral Accords",
    base: "Musk, Woods, Resinous Warmth",
    price: 249
  },
  {
    id: 103,
    name: "Musk Tahara",
    image: "muskt.jpg",
    images: ["muskt.jpg", "muskt1.jpg", "muskt2.jpg", "info.jpg"],
    description: "A pure and clean white musk fragrance with soft powdery freshness, ideal for daily wear.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky Clean",
    accords: ["Fresh", "Musky", "Powdery"],
    top: "White Musk",
    mid: "",
    base: "",
    price: 99
  },
  {
    id: 104,
    name: "Musk Tahara Premium",
    image: "musktpa.jpg",
    images: ["musktpa.jpg", "musktpa1.jpg", "musktpa2.jpg", "infoa.jpg"],
    description: "A premium and longer-lasting white musk attar with enhanced smoothness and purity.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Musky Clean",
    accords: ["Fresh", "Musky", "Powdery"],
    top: "White Musk",
    mid: "",
    base: "",
    price: 239
  },
  {
    id: 105,
    name: "Badar",
    image: "badara.jpg",
    images: ["badara.jpg", "badara1.jpg", "badara2.jpg", "infoa.jpg"],
    description: "A balanced woody-musky fragrance with floral softness and warm amber undertones.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day/Night",
    family: "Woody Musky",
    accords: ["Woody", "Musky", "Floral"],
    top: "Honey",
    mid: "Rose, Lavender",
    base: "Musk, Amber, Patchouli",
    price: 249
  },
  {
    id: 106,
    name: "Kuwaiti OUD",
    image: "kuwaitioa.jpg",
    images: ["kuwaitioa.jpg", "kuwaitioa1.jpg", "kuwaitioa2.jpg", "infoa.jpg"],
    description: "A rich and spicy oud fragrance with earthy warmth and smooth vanilla undertones.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Spicy", "Earthy"],
    top: "Rosemary, Cardamom, Ginger",
    mid: "Saffron, Jasmine, Tonka Bean",
    base: "Amber, Sandalwood, Vanilla, Oud, Patchouli, Musk",
    price: 149
  },
  {
    id: 107,
    name: "Kuwaiti OUD Premium",
    image: "kuwaitiopa.jpg",
    images: ["kuwaitiopa.jpg", "kuwaitiopa1.jpg", "kuwaitiopa2.jpg", "infoa.jpg"],
    description: "A premium and more intense interpretation of Kuwaiti Oud with enhanced depth and longevity.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Spicy", "Earthy"],
    top: "Rosemary, Cardamom, Ginger",
    mid: "Saffron, Jasmine, Tonka Bean",
    base: "Amber, Sandalwood, Vanilla, Oud, Patchouli, Musk",
    price: 279
  },
  {
    id: 108,
    name: "Mysore Sandal",
    image: "mysorea.jpg",
    images: ["mysorea.jpg", "mysorea1.jpg", "mysorea2.jpg", "infoa.jpg"],
    description: "A pure and creamy sandalwood fragrance sourced from Mysore, smooth, meditative, and timeless.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Woody",
    accords: ["Woody", "Vanilla", "Musky"],
    top: "Sandalwood from Mysore",
    mid: "",
    base: "",
    price: 279
  },
  {
    id: 109,
    name: "Seufi OUD",
    image: "seufioa.jpg",
    images: ["seufioa.jpg", "seufioa1.jpg", "seufioa2.jpg", "infoa.jpg"],
    description: "A floral-woody oriental fragrance with musky softness and rich Indian oud depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Floral", "Woody", "Oriental"],
    top: "Mitti",
    mid: "Musk",
    base: "Agarwood (Indian Oud)",
    price: 299
  },
  {
    id: 110,
    name: "Indian OUD",
    image: "indianoa.jpg",
    images: ["indianoa.jpg", "indianoa1.jpg", "indianoa2.jpg", "infoa.jpg"],
    description: "A raw and intense Indian oud fragrance with smoky depth and earthy richness.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Oriental", "Smoky"],
    top: "Agarwood (Indian Oud)",
    mid: "",
    base: "",
    price: 499
  },
  {
    id: 111,
    name: "Thailand OUD",
    image: "thailandoa.jpg",
    images: ["thailandoa.jpg", "thailandoa1.jpg", "thailandoa2.jpg", "infoa.jpg"],
    description: "A refined Thai oud fragrance with spicy warmth and subtle sweetness.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Oriental Spicy", "Subtle Sweet"],
    top: "Agarwood (Thailand Oud)",
    mid: "",
    base: "",
    price: 499
  },
  {
    id: 112,
    name: "Cambodian OUD",
    image: "cambodianoa.jpg",
    images: ["cambodianoa.jpg", "cambodianoa1.jpg", "cambodianoa2.jpg", "infoa.jpg"],
    description: "A smooth Cambodian oud with mossy undertones and rich oriental warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Oriental", "Mossy"],
    top: "Agarwood (Cambodian Oud)",
    mid: "",
    base: "",
    price: 499
  },
  {
    id: 113,
    name: "Freshka",
    image: "freshka.jpg",
    images: ["freshka.jpg", "freshka1.jpg", "freshka2.jpg", "info.jpg"],
    description: "A bright and refreshing musky-floral fragrance with citrus freshness and clean elegance.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Musky",
    accords: ["Fresh", "Musky", "Floral"],
    top: "Bergamot, Lemon",
    mid: "Lily of the Valley, Jasmine",
    base: "Musk, Amber, Sandalwood",
    price: 349
  },
  {
    id: 114,
    name: "Sandaliya",
    image: "sandaliyaa.jpg",
    images: ["sandaliyaa.jpg", "sandaliyaa1.jpg", "sandaliyaa2.jpg", "infoa.jpg"],
    description: "A deep sandalwood-centric fragrance with earthy spice and woody warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Woody Earthy",
    accords: ["Citrus Spicy", "Earthy", "Woody"],
    top: "Sandalwood",
    mid: "",
    base: "",
    price: 899
  },
  {
    id: 115,
    name: "Dehnal OUD Combodi Qadim",
    image: "dehnalca.jpg",
    images: ["dehnalca.jpg", "dehnalca1.jpg", "dehnalca2.jpg", "infoa.jpg"],
    description: "An aged Cambodian oud attar offering deep honeyed richness and elegant woody warmth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Honey", "Spicy", "Elegant"],
    top: "Aged Cambodian Oud",
    mid: "",
    base: "",
    price: 899
  },
  {
    id: 116,
    name: "Dahnal OUD Hindi Qadim",
    image: "dehnalha.jpg",
    images: ["dehnalha.jpg", "dehnalha1.jpg", "dehnalha2.jpg", "infoa.jpg"],
    description: "An aged Indian oud fragrance showcasing deep woody intensity with honeyed warmth and natural spice.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Oriental",
    accords: ["Woody", "Honey", "Spicy"],
    top: "Aged Indian Oud",
    mid: "",
    base: "",
    price: 899
  },
  {
    id: 117,
    name: "Fire OUD",
    image: "Fire OUD.png",
    images: ["Fire OUD.png", "fireo1.jpg", "fireo2.jpg", "info.jpg"],
    description: "A bold woody-leather fragrance with aromatic freshness and smoky warmth.",
    category: "Perfume",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Woody", "Leather", "Aromatic"],
    top: "Geranium, Leather",
    mid: "Cedar, Patchouli",
    base: "Moss, Musk, Amber",
    price: 175
  },
  {
    id: 118,
    name: "Fire OUD",
    image: "fireoa.jpg",
    images: ["fireoa.jpg", "fireoa1.jpg", "fireoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar version delivering intense leather-woody richness with smoky depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Woody",
    accords: ["Woody", "Leather", "Aromatic"],
    top: "Geranium, Leather",
    mid: "Cedar, Patchouli",
    base: "Moss, Musk, Amber",
    price: 175
  },
  {
    id: 119,
    name: "Ruh Khus",
    image: "ruhkhusa.jpg",
    images: ["ruhkhusa.jpg", "ruhkhusa1.jpg", "ruhkhusa2.jpg", "infoa.jpg"],
    description: "A pure vetiver fragrance offering earthy freshness, green herbal tones, and cooling depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Summer",
    time: "Day",
    family: "Green Earthy",
    accords: ["Fresh", "Green Herbal", "Earthy"],
    top: "Vetiver (Khus)",
    mid: "",
    base: "",
    price: 599
  },
  {
    id: 120,
    name: "Fume Vanille",
    image: "Fume Vanille.png",
    images: ["Fume Vanille.png", "fumev1.jpg", "fumev2.jpg", "info.jpg"],
    description: "A warm oriental gourmand fragrance blending tobacco spice with creamy vanilla sweetness.",
    category: "Perfume",
    inspiredBy: "Tobacco Vanille",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Oriental", "Gourmand", "Smoky"],
    top: "Tobacco Leaf, Spicy Notes",
    mid: "Vanilla, Cacao, Tonka Bean, Tobacco Blossom",
    base: "Dried Fruits, Woody Notes",
    price: 99
  },
  {
    id: 121,
    name: "Fume Vanille",
    image: "fumeva.jpg",
    images: ["fumeva.jpg", "fumeva1.jpg", "fumeva2.jpg", "infoa.jpg"],
    description: "A rich attar version delivering deep vanilla sweetness and smoky tobacco warmth.",
    category: "Attar",
    inspiredBy: "Tobacco Vanille",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Oriental", "Gourmand", "Smoky"],
    top: "Tobacco Leaf, Spicy Notes",
    mid: "Vanilla, Cacao, Tonka Bean, Tobacco Blossom",
    base: "Dried Fruits, Woody Notes",
    price: 89
  },
  {
    id: 122,
    name: "Al Dahab",
    image: "aldahaba.jpg",
    images: ["aldahaba.jpg", "aldahaba1.jpg", "aldahaba2.jpg", "infoa.jpg"],
    description: "A luxurious fruity-floral fragrance with woody sweetness and golden warmth.",
    category: "Attar",
    inspiredBy: "Wisal Dahab",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Floral Woody",
    accords: ["Dark Wood", "Sweet", "Floral"],
    top: "Pear, Apple, Peach, Grapefruit, Mandarin Orange",
    mid: "Rose, Orchid, Jasmine, Geranium",
    base: "Sandalwood, Musk, Cedar, Patchouli",
    price: 129
  },
  {
    id: 123,
    name: "Eternal Elixir",
    image: "eternalela.jpg",
    images: ["eternalela.jpg", "eternalela1.jpg", "eternalela2.jpg", "infoa.jpg"],
    description: "A bold spicy-woody fragrance with aromatic lavender and rich resinous warmth.",
    category: "Attar",
    inspiredBy: "Sauvage Elixir",
    gender: "Male",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Floral", "Spicy"],
    top: "Nutmeg, Cinnamon, Cardamom, Grapefruit",
    mid: "Lavender",
    base: "Licorice, Sandalwood, Amber, Patchouli, Haitian Vetiver",
    price: 89
  },
  
  {
    id: 125,
    name: "Silver Mist",
    image: "silverma.jpg",
    images: ["silverma.jpg", "silverma1.jpg", "silverma2.jpg", "infoa.jpg"],
    description: "A long-lasting attar version combining fresh citrus, green tea, and smooth musk.",
    category: "Attar",
    inspiredBy: "Creed Silver MW",
    gender: "Male",
    season: "Spring-Summer",
    time: "Day",
    family: "Fresh Woody",
    accords: ["Fresh", "Woody", "Musky"],
    top: "Bergamot, Mandarin Orange",
    mid: "Green Tea, Black Currant",
    base: "Musk, Sandalwood, Petitgrain, Galbanum",
    price: 89
  },
 
  {
    id: 127,
    name: "Rose OUD",
    image: "roseouda.jpg",
    images: ["roseouda.jpg", "roseouda1.jpg", "roseouda2.jpg", "infoa.jpg"],
    description: "A concentrated attar version highlighting the richness of rose layered over oud.",
    category: "Attar",
    inspiredBy: "OUD And Roses",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Floral",
    accords: ["Woody", "Oriental", "Citrus"],
    top: "Rose",
    mid: "Rose",
    base: "Agarwood (Oud)",
    price: 89
  },
  {
    id: 128,
    name: "Mafia Oud",
    image: "mafiaouda.jpg",
    images: ["mafiaouda.jpg", "mafiaouda1.jpg", "mafiaouda2.jpg", "infoa.jpg"],
    description: "A dark smoky oud fragrance with earthy woods and subtle fruity undertones.",
    category: "Attar",
    inspiredBy: "Mafia OUD",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Oriental", "Smoky"],
    top: "Oud, Musk, Patchouli",
    mid: "Sandalwood, Vetiver, Vanilla",
    base: "Woody, Smoky, Fruity, Earthy",
    price: 149
  },
  {
    id: 129,
    name: "Badee Al OUD",
    image: "badeeoa.jpg",
    images: ["badeeoa.jpg", "badeeoa1.jpg", "badeeoa2.jpg", "infoa.jpg"],
    description: "A modern spicy-oud fragrance blending aromatic freshness with warm woody richness.",
    category: "Attar",
    inspiredBy: "Badee Al OUD",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Spicy",
    accords: ["Woody", "Warm Spicy", "Fresh Spicy"],
    top: "Saffron, Nutmeg, Lavender",
    mid: "Oud, Patchouli",
    base: "Oud, Patchouli, Musk",
    price: 99
  },
  {
    id: 130,
    name: "Arabian Tonka",
    image: "arabiantonka.jpg",
    images: ["arabiantonka.jpg", "arabiantonka1.jpg", "arabiantonka2.jpg", "infoa.jpg"],
    description: "A rich gourmand-oriental fragrance with sweet tonka bean and warm amber depth.",
    category: "Attar",
    inspiredBy: "Arabian Tonka",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Gourmand",
    accords: ["Oriental", "Gourmand", "Woody"],
    top: "Saffron, Bergamot",
    mid: "Oud, Bulgarian Rose",
    base: "Tonka Bean, Sugar Cane, Amber, White Musk, Oakmoss",
    price: 99
  },
  {
    id: 131,
    name: "Musk Rose",
    image: "muskrosea.jpg",
    images: ["muskrosea.jpg", "muskrosea1.jpg", "muskrosea2.jpg", "infoa.jpg"],
    description: "A romantic floral-musky fragrance where fresh roses blend with soft spices and creamy woods.",
    category: "Attar",
    inspiredBy: "Musk Rose",
    gender: "Unisex",
    season: "All seasons",
    time: "Day",
    family: "Floral Musky",
    accords: ["Floral", "Spicy", "Musky"],
    top: "Bergamot, Peach, Apple, Pear",
    mid: "Cyclamen, Freesia, Rose",
    base: "Sandalwood, Cedarwood, Vanilla, Amber, Musk",
    price: 99
  },
  {
    id: 132,
    name: "Amber River",
    image: "amberrivera.jpg",
    images: ["amberrivera.jpg", "amberrivera1.jpg", "amberrivera2.jpg", "infoa.jpg"],
    description: "A warm fruity-amber fragrance with spicy undertones and smooth resinous depth.",
    category: "Attar",
    inspiredBy: "Hudson Valley",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Spicy",
    accords: ["Fruity", "Warm Spicy", "Amber"],
    top: "Black Currant, Saffron",
    mid: "Rose",
    base: "Amber, Patchouli",
    price: 99
  },
  {
    id: 133,
    name: "Al Lail",
    image: "allaila.jpg",
    images: ["allaila.jpg", "allaila1.jpg", "allaila2.jpg", "infoa.jpg"],
    description: "A sensual fruity-floral fragrance with oud richness and incense warmth, elegant and mysterious.",
    category: "Attar",
    inspiredBy: "Wisal Lail",
    gender: "Female",
    season: "Autumn-Winter",
    time: "Night",
    family: "Floral Woody",
    accords: ["Fruity", "Floral", "Woody"],
    top: "Blackcurrant, Apricot, Freesia",
    mid: "Rose, Patchouli, Osmanthus",
    base: "Musk, Oud, Frankincense",
    price: 129
  },
  {
    id: 134,
    name: "Rooh Gulab",
    image: "rooh gulab.png",
    images: ["rooh gulab.png", "roohgula1.jpg", "roohgula2.jpg", "infoa.jpg"],
    description: "A pure and natural rose distillation capturing the essence of fresh blooming roses.",
    category: "Attar",
    inspiredBy: "Rooh Gulab",
    gender: "Unisex",
    season: "Spring-Summer",
    time: "Day",
    family: "Floral",
    accords: ["Rose Floral"],
    top: "Rose",
    mid: "",
    base: "",
    price: 129
  },
  {
    id: 135,
    name: "Tobacco OUD",
    image: "tobaccoouda.jpg",
    images: ["tobaccoouda.jpg", "tobaccoouda1.jpg", "tobaccoouda2.jpg", "infoa.jpg"],
    description: "A dark and intense blend of tobacco smoke and oud with spicy warmth and resinous sweetness.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Smoky",
    accords: ["Woody", "Leathery", "Tobacco"],
    top: "Whiskey",
    mid: "Spicy Notes, Cinnamon, Coriander",
    base: "Tobacco, Oud, Incense, Sandalwood, Patchouli, Benzoin, Vanilla, Cedar",
    price: 129
  },
  {
    id: 136,
    name: "Arabian OUD",
    image: "arabianouda.jpg",
    images: ["arabianouda.jpg", "arabianouda1.jpg", "arabianouda2.jpg", "infoa.jpg"],
    description: "A smooth and powdery oud fragrance with warm spices and oriental depth.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Powdery", "Warm Spicy"],
    top: "",
    mid: "",
    base: "",
    price: 129
  },
  {
    id: 137,
    name: "Bin Sheikh",
    image: "binsheikha.jpg",
    images: ["binsheikha.jpg", "binsheikha1.jpg", "binsheikha2.jpg", "infoa.jpg"],
    description: "A rich amber-oud fragrance with floral sweetness and smoky oriental warmth.",
    category: "Attar",
    inspiredBy: "AM BIN SHEIKH",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Oriental",
    accords: ["Amber", "Oud", "Sweet"],
    top: "Saffron, Rose, Oakmoss, Lavender, Citruses",
    mid: "Sugar, Bakhoor, Jasmine, Orchid, Violet",
    base: "Oud, Amber, Ambroxan, Patchouli, White Musk",
    price: 129
  },
  
  {
    id: 139,
    name: "Dark Silhouette",
    image: "darksla.jpg",
    images: ["darksla.jpg", "darksla1.jpg", "darksla2.jpg", "infoa.jpg"],
    description: "A concentrated attar version with deep leather intensity and smooth amber warmth.",
    category: "Attar",
    inspiredBy: "TF Ombre Leather",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Spicy",
    accords: ["Leather", "Animalic", "Warm Spicy"],
    top: "Cardamom",
    mid: "Leather, Jasmine Sambac",
    base: "Amber, Moss, Patchouli",
    price: 89
  },
  {
    id: 140,
    name: "Silk Oud",
    image: "silkouda.jpg",
    images: ["silkouda.jpg", "silkouda1.jpg", "silkouda2.jpg", "infoa.jpg"],
    description: "A refined floral-woody oud fragrance with herbal softness and smooth resinous depth.",
    category: "Attar",
    inspiredBy: "MFK Silk OUD",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Woody Floral",
    accords: ["Herbal", "Woody", "Floral"],
    top: "Bulgarian Rose, Chamomile, Bergamot",
    mid: "Guaiac Wood, Hedione",
    base: "Oud, Papyrus",
    price: 89
  },
  {
    id: 141,
    name: "Shamama",
    image: "shamamaa.jpg",
    images: ["shamamaa.jpg", "shamamaa1.jpg", "shamamaa2.jpg", "infoa.jpg"],
    description: "A traditional complex attar blending woods, florals, and powdery warmth with deep heritage character.",
    category: "Attar",
    inspiredBy: "",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Woody",
    accords: ["Woody", "Floral", "Powdery"],
    top: "",
    mid: "",
    base: "",
    price: 149
  },
  {
    id: 142,
    name: "Ruh Al Wadi",
    image: "ruhalwadia.jpg",
    images: ["ruhalwadia.jpg", "ruhalwadia1.jpg", "ruhalwadia2.jpg", "infoa.jpg"],
    description: "A powerful aromatic-leather fragrance with oud richness and spicy freshness.",
    category: "Attar",
    inspiredBy: "Imperial Valley",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Leather Aromatic",
    accords: ["Woody", "Aromatic", "Leather"],
    top: "Sicilian Bergamot, Pink Pepper, Davana",
    mid: "Oud, White Amber, Rosemary",
    base: "Leather, Musk, Haitian Vetiver",
    price: 129
  },

  {
    id: 144,
    name: "Ombre",
    image: "ombrea.jpg",
    images: ["ombrea.jpg", "ombrea1.jpg", "ombrea2.jpg", "infoa.jpg"],
    description: "A deep and intense attar version with smoky oud, amber richness, and spicy warmth.",
    category: "Attar",
    inspiredBy: "Ombre Nomade",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Amber Woody",
    accords: ["Amber", "Woody", "Warm Spicy"],
    top: "Saffron, Rose",
    mid: "Amberwood, Benzoin",
    base: "Amber, Oud, Spicy, Smoky",
    price: 139
  },
 
  {
    id: 146,
    name: "Satin OUD",
    image: "satinoa.jpg",
    images: ["satinoa.jpg", "satinoa1.jpg", "satinoa2.jpg", "infoa.jpg"],
    description: "A concentrated attar version of a luxurious rose-oud composition with creamy vanilla and amber warmth.",
    category: "Attar",
    inspiredBy: "MFK oud Satin Mood",
    gender: "Unisex",
    season: "Autumn-Winter",
    time: "Night",
    family: "Oriental Floral",
    accords: ["Rose", "Floral", "Oud", "Amber", "Vanilla", "Powdery"],
    top: "Bulgarian Rose, Violet, Strawberry",
    mid: "Turkish Rose",
    base: "Oud (Agarwood), Vanilla, Amber, Benzoin, Caramel, Cedar",
    price: 89
  },
  // {
  //   id: 147,
  //   name: "Citrus Bloom",
  //   image: "citrusb.jpg",
  //   images: ["citrusb.jpg", "citrusb1.jpg", "citrusb2.jpg", "info.jpg"],
  //   description: "A bright and elegant citrus-floral fragrance with woody depth and soft musky sensuality.",
  //   category: "Perfume",
  //   inspiredBy: "Coco Chanel mademoiselle",
  //   gender: "Female",
  //   season: "All seasons",
  //   time: "Day/Night",
  //   family: "Floral Citrus",
  //   accords: ["Citrus", "Floral", "Woody", "Musky"],
  //   top: "Orange, Bergamot, Mandarin",
  //   mid: "Jasmine, Rose, Ylang-Ylang, Mimosa, Iris",
  //   base: "Patchouli, Vetiver, Vanilla, White Musk, Opoponax, Tonka Bean",
  //   price: 89
  // },
  
 

  

];

await Product.deleteMany(); // optional (clean start)
await Product.insertMany(products);

console.log('✅ Products seeded successfully');
process.exit();